#!/usr/bin/env bash
# This will Configure your Nginx server so that /redirect_me is redirecting to another page.
# The redirection is configured as a "301 Moved Permanently"

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/EdwinKamau2 permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/ngninx/sites-enabled/default

sudo service nginx restart
