#!/usr/bin/env bash
# Install your load balancer

apt-get update
apt-get -y install haproxy

sed -i -e '$ afrontend http_front \n\tbind *:80 \
\tmode http \
\tdefault_backend http_rear \
\nbackend http_rear \
\tbalance		roundrobin \
\tserver 269030-web-01		52.86.218.252:80 check \
\tserver 269030-web-02		34.207.211.58:80 check' /etc/haproxy/haproxy.cfg

service haproxy restart
